name: .NET CI - Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore
        working-directory: TaskManagementAPI  # Ensure commands run inside the project folder

      - name: Install Missing Packages (Workaround for Newtonsoft.Json Issue)
        run: dotnet add package Newtonsoft.Json --version 13.0.1
        working-directory: TaskManagementAPI  # Ensure package is installed inside the correct project

      - name: Build the Application
        run: dotnet build --no-restore
        working-directory: TaskManagementAPI  # Ensure build runs in the correct directory

      - name: Run Unit Tests
        run: dotnet test --no-build --verbosity normal
        working-directory: TaskManagementAPI.Tests  # Ensure tests run inside the test project directory
