name: .NET CI - Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore TaskManagementAPI.sln  # ✅ Ensure dependencies are restored using the solution file

      - name: Build the Application
        run: dotnet build TaskManagementAPI.sln --no-restore  # ✅ Ensure build runs for the entire solution

      - name: Run Unit Tests
        run: dotnet test TaskManagementAPI.sln --no-build --verbosity normal  # ✅ Run tests using the solution file
